version: '3.4'

services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root_password
      - POSTGRES_USER=root
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
