DROP TABLE IF EXISTS t_book;

CREATE TABLE t_book (
    id BIGSERIAL NOT NULL UNIQUE,
    isbn VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    PRIMARY KEY (id)
)